# Specify the version of docker compose that we want to run
version: '3.8'

# We can specify multiple services that we want to orchestrate
services:
  # Backend API
  smart-brain-api:
    container_name: backend
    # We can build our own Dockerfile instead of importing separate images here - specify the dir for the Dockerfile
    build: ./
    # The command to run when our container is running (-- -L flag fixes issue with nodemon on Windows)
    command: npm start -- -L
    working_dir: /usr/src/smart-brain-api
    # We can declare separate env variables under 'environment', or the .env file we want to use instead
    env_file:
      - docker.env
    # Port forwarding - specify which port to open the app on locally
    ports:
      - "5000:5000"
    # Allows us to map our root directory to the docker app root directory to ensure it watches for changes
    volumes:
      - ./:/usr/src/smart-brain-api

  # Postgres
  postgres:
    # Don't need a container named postgres, as the image already has a container with this name
    env_file:
      - postgres.env
    # Build the Dockerfile in the postgres directory
    build: ./postgres
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"
